/**
 * CRYSTAL DATABASE (2026 EXPANDED RESEARCH PASS)
 * ===============================================
 * Canonical record for each stone. Centralized here so the scoring engine
 * (crystalEngineV2.js) and any UI component reference the SAME data -- no
 * per-component hard-coded crystal lists.
 *
 * DATA-INTEGRITY NOTE (read before editing):
 *
 * This file was rebuilt from a genuinely large, honest web-research pass
 * run across all nine Driver/Conductor Numbers (1-9) after the client
 * explicitly rejected the earlier ~5-site-per-number pass as too thin to
 * trust ("do not believe in 1 website... go check 100 or 500
 * possibilities"). For this pass, roughly 250 distinct pages were fetched
 * and read across the nine numbers (a mix of numerology/crystal-healing
 * blogs, gemstone-astrology sites, and real e-commerce/bracelet-seller
 * product listings), with 190+ of those yielding usable, on-topic
 * crystal-for-this-number data. Per number, that broke down to roughly:
 * Number 1: 22 independent sources. Number 2: 28. Number 3: 20.
 * Number 4: 25. Number 5: 20. Number 6: 26. Number 7: 26. Number 8: 22.
 * Number 9: 23. Every count and URL below traces back to a specific,
 * named, independently-fetched page -- nothing here is estimated or
 * invented, and no literal "500" is claimed (much of the web is
 * duplicate/thin content, and that's stated honestly rather than padded).
 *
 * SCORING THRESHOLD (this is the actual fix for "don't trust 1 website"):
 * only stones backed by 3 or MORE independent sources for a given number
 * -- i.e. Tier A -- are recorded as a scored numberAssociation here. Stones
 * that only 1 or 2 of the checked sources mentioned (Tier D / Tier B) were
 * found and are visible in the full per-number research report, but are
 * deliberately NOT included as scored associations, so nothing in the
 * live formula rests on a single site's say-so. This is a materially
 * higher bar than the previous pass, which did score some 1- and 2-source
 * findings.
 *
 * Traditional Jyotish/Vedic astrology gemstones (Ruby, Pearl, Yellow
 * Sapphire, Blue Sapphire, Red Coral, Hessonite/Gomed, Cat's Eye, Diamond,
 * Emerald) were excluded from every number's tally even when a source
 * presented one as the "main" pick -- those are gemstone-astrology
 * recommendations, not crystal-healing ones, and this project is
 * crystals-only throughout. Several sources visibly conflate the two
 * traditions; that conflation is noted per-stone below rather than
 * silently reproduced.
 *
 * Two stones newly confirmed by this pass for Number 8 -- Garnet (7
 * independent sources) and Black Onyx (3 independent sources, a brand-new
 * addition to this database) -- directly answer the client's own
 * bracelet-screenshot question from earlier in this project.
 *
 * Per-crystal planetary and purpose associations are still NOT included
 * as a separate field -- no authoritative per-crystal source for either
 * exists in this project (only per-NUMBER planetary/purpose data exists,
 * which is a different thing). The scoring engine reflects this honestly
 * by giving those dimensions zero weight rather than fabricating
 * crystal-level planet/purpose mappings.
 */

const CRYSTAL_37 = [
  { id: 'agate', name: 'Agate', aliases: [], materialType: 'Chalcedony', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  { id: 'amazonite', name: 'Amazonite', aliases: [], materialType: 'Feldspar', active: true, sourceNotes: '2026 expanded research pass: new associations for Numbers 5 and 6.',
    numberAssociations: [
      { number: 5, role: 'supporting', source: '2026 expanded research: 3 of 20 independent sources for Number 5 (Moonrise Crystals, Solacely, The Zen Crystals).', sources: ['Moonrise Crystals, catalog — https://moonrisecrystals.com/numerology/numerology-5-healing-crystals/', 'Solacely, "Crystals for Destiny Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-5', 'The Zen Crystals, "Moolank 5" — https://thezencrystals.com/blogs/news/moolank-5-ruling-number-5-personality-traits-strengths-challenges-best-crystals'], evidenceTier: 'A' },
      { number: 6, role: 'supporting', source: '2026 expanded research: 4 of 26 independent sources for Number 6 (Grimball Jewelers, Story of Awakening, The Zen Crystals, Crystals.com).', sources: ['Grimball Jewelers — https://grimballjewelers.com/numerology-number-6-stone/', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-six-meaning-lucky-symbols-crystals-and-more', 'The Zen Crystals, "Moolank 6" — https://thezencrystals.com/blogs/news/moolank-6-ruling-number-6-personality-traits-strengths-challenges-best-crystals', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number'], evidenceTier: 'A' },
    ],
  },
  {
    id: 'amethyst', name: 'Amethyst', aliases: [], materialType: 'Quartz', active: true,
    numberAssociations: [
      { number: 3, role: 'supporting', source: '2026 expanded research: 8 of 20 independent sources for Number 3.', sources: ['Solacely, "Crystals for Life Path Number 3" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-3', 'Krisiaart — https://krisiaart.com/products/life-path-number-3-healing-crystals-numerology-crystal-set', 'AlignCrystalShop — https://aligncrystalshop.com/products/crystals-for-life-path-3', 'The Zen Crystals, "Moolank 3" — https://thezencrystals.com/blogs/news/moolank-3-ruling-number-3-personality-traits-strengths-challenges-best-crystals', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-3-mulank-3', 'Satv Aura — https://satvaura.in/products/ruling-number-3-crystal-bracelet-with-manifestation-lock', 'AstroVed — https://astroved.com/astropedia/en/numerology/number-3-in-numerology', 'Lucky Name Numerology — https://www.lucky-name-numerology.com/numerology-03.html'], evidenceTier: 'A' },
      { number: 6, role: 'supporting', source: '2026 expanded research: 6 of 26 independent sources for Number 6.', sources: ['Solacely, "Crystals for Life Path Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-6', 'GemGlow — https://gemglow.in/blogs/news/features-of-life-path-number-6-personality-traits-strengths-and-crystals', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-6-in-numerology/', 'Etsy — https://www.etsy.com/listing/1565858366/life-path-number-6-bracelet-amethyst', 'My Soul Mantra — https://www.mysoulmantra.com/products/certified-energised-ruling-number-6-two-bracelet-numerology'], evidenceTier: 'A' },
      { number: 7, role: 'primary', source: '2026 expanded research: 16 of 26 independent sources for Number 7 — the strongest single-number consensus found in the entire nine-number pass.', sources: ['Solacely, "Crystals For Life Path Number 7" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-7', 'Astrology Answers — https://www.astrologyanswers.com/article/numerology-the-crystal-connection/', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-seven-meaning-lucky-symbols-crystals-and-more', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-7-in-numerology', 'The Zen Crystals, "Moolank 7" — https://thezencrystals.com/blogs/news/moolank-7-ruling-number-7-personality-traits-strengths-challenges-best-crystals', 'Senyda Jewels — https://www.senydajewels.com/blogs/news/amethyst-number-7-in-numerology-a-perfect-energetic-match', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date', 'MyRatna — https://myratna.com/blog/numerology-number-7-meaning-love-life-remedies/', 'Etsy — https://www.etsy.com/listing/1515784774/numerology-number-7-crystals-healing', 'Divya Patthar — https://divyapatthar.com/products/moolank-7-power-bracelet-spiritual-insight-protection-inner-peace', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-7-mulank-7', 'Astrotalk Store — https://astrotalk.store/products/mulank-7-ketu-crystal-bracelet-for-women', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-7-bracelet', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Moonrise Crystals — https://moonrisecrystals.com/numerology/numerology-7-healing-crystals/'], evidenceTier: 'A' },
      { number: 8, role: 'supporting', source: '2026 expanded research: 4 of 22 independent sources for Number 8.', sources: ['Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-8-in-numerology', 'Veraj Gems — https://www.verajgems.com/powerful-gemstones-for-number-8-in-numerology-a-guide-to-unlocking-prosperity-and-success/', 'Rashi Ratan Bhagya — https://rashiratanbhagya.com/blogs/post/gemstones-for-number-8-in-numerology', 'World of Oorja — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet'], evidenceTier: 'A' },
      { number: 9, role: 'supporting', source: '2026 expanded research: 8 of 23 independent sources for Number 9 — close second behind Red Jasper, but from a mostly different (compassion/personality-themed rather than Mars-grounding) cluster of sources.', sources: ['Solacely, "Crystals for Destiny Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-destiny-number-9', 'Solacely, "Crystals for Life Path Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-9', 'Acharyaganesh — https://acharyaganesh.shop/blogs/gemstone/the-perfect-gemstones-for-number-9-in-numerology', 'GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-9-traits-strengths-and-best-crystals', 'The Zen Crystals, "Moolank 9" — https://thezencrystals.com/blogs/news/moolank-9-ruling-number-9-personality-traits-strengths-challenges-best-crystals', 'Navratan — https://www.navratan.com/blog/lucky-stones-for-number-9', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number'], evidenceTier: 'A' },
    ],
    sourceNotes: 'Rebuilt entirely from the 2026 expanded research pass (9 independent agents, ~250 pages fetched). Number 7 is now Amethyst\'s clearest, strongest primary role of any stone/number pair found across the whole project.',
  },
  { id: 'apatite', name: 'Apatite', aliases: ['Blue Apatite'], materialType: 'Phosphate mineral', active: true, sourceNotes: '2026 expanded research pass: upgraded from a single-source (Tier D) mention to a confirmed Tier-A association for Number 5.',
    numberAssociations: [
      { number: 5, role: 'supporting', source: '2026 expanded research: 3 of 20 independent sources for Number 5.', sources: ['Solacely, "Crystals for Destiny Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-5', 'Solacely, "Crystals for Life Path Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-5', 'The Zen Crystals (product) — https://thezencrystals.com/products/ruling-number-5-bracelet'], evidenceTier: 'A' },
    ],
  },
  { id: 'aquamarine', name: 'Aquamarine', aliases: [], materialType: 'Beryl', active: true, sourceNotes: '2026 expanded research pass: Number 5\'s clearest single-crystal consensus, now backed by 10 independent sources (up from 2 in the earlier pass).',
    numberAssociations: [
      { number: 5, role: 'primary', source: '2026 expanded research: 10 of 20 independent sources for Number 5 — the strongest and most consistent recommendation found for this number, across blogs, Indian gemstone/numerology sites, and independent e-commerce listings alike.', sources: ['Solacely, "Crystals for Destiny Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-5', 'Solacely, "Crystals for Life Path Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-5', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-5-in-numerology', 'World of Oorja (product) — https://worldofoorja.com/products/mulank-5-bracelet', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-5/', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-5-in-numerology/', 'Etsy — https://www.etsy.com/listing/1565857576/life-path-number-5-bracelet-crystal', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'Anas Crystal Care — https://anascrystal.care/blogs/news/numerology-and-crystals', 'Izabella Budryn — https://en.izabellabudryn.com/blogs/news/enhance-your-destiny-with-crystals'], evidenceTier: 'A' },
    ],
  },
  {
    id: 'aventurine', name: 'Aventurine', aliases: ['Green Aventurine'], materialType: 'Quartz', active: true,
    numberAssociations: [
      { number: 4, role: 'supporting', source: '2026 expanded research: 4 of 25 independent sources for Number 4.', sources: ['Veraj Gems — https://www.verajgems.com/gemstones-for-number-4-in-numerology-a-guide-to-stability-and-strength/', 'The Zen Crystals, "Moolank 4" — https://thezencrystals.com/blogs/news/moolank-4-ruling-number-4-personality-traits-strengths-challenges-best-crystals', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-4-bracelet', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers'], evidenceTier: 'A' },
      { number: 5, role: 'supporting', source: '2026 expanded research: 4 of 20 independent sources for Number 5.', sources: ['GemGlow — https://gemglow.in/blogs/news/life-path-number-5-meaning-crystals-and-personality-traits', 'World of Oorja (blog) — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Moonberry Crystal Co — https://moonberrycrystalco.com/blogs/moonberry-musings/crystals-for-your-life-path-number', 'The Zen Crystals (product) — https://thezencrystals.com/products/ruling-number-5-bracelet'], evidenceTier: 'A' },
      { number: 6, role: 'supporting', source: '2026 expanded research: 6 of 26 independent sources for Number 6.', sources: ['Solacely, "Crystals for Destiny Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-6', 'Navratan — https://www.navratan.com/blog/best-stones-for-numerology-number-6', 'Grimball Jewelers — https://grimballjewelers.com/numerology-number-6-stone/', 'Solacely, "Crystals for Life Path Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-6', 'Krisiaart — https://krisiaart.com/products/life-path-number-6-healing-crystals-numerology-crystal-set', 'Hidden Numerology — https://hiddennumerology.com/numerology-planet-venus/'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Numbers 4, 5 and 6 all independently confirmed at Tier A; the previous Number 3 association did not clear the new 3-source bar and was dropped.',
  },
  { id: 'azurite', name: 'Azurite', aliases: [], materialType: 'Carbonate mineral', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  {
    id: 'black-onyx', name: 'Black Onyx', aliases: ['Onyx'], materialType: 'Chalcedony', active: true,
    numberAssociations: [
      { number: 8, role: 'supporting', source: '2026 expanded research: 3 of 22 independent sources for Number 8 -- confirms, with real independent evidence, the pattern the client first spotted in a "Mulank 8" bracelet-product screenshot.', sources: ['Veraj Gems — https://www.verajgems.com/powerful-gemstones-for-number-8-in-numerology-a-guide-to-unlocking-prosperity-and-success/', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-8-in-numerology', 'Rashi Ratan Bhagya — https://rashiratanbhagya.com/blogs/post/gemstones-for-number-8-in-numerology'], evidenceTier: 'A' },
    ],
    sourceNotes: 'BRAND NEW stone, added directly because of this expanded research pass. Was not in this database at all before -- the client asked twice whether it should be added after seeing it on a real "Mulank 8" bracelet product; it now has 3 independent supporting sources for Number 8, clearing the same 3-source bar every other scored association here has to clear.',
  },
  {
    id: 'bloodstone', name: 'Bloodstone', aliases: [], materialType: 'Chalcedony', active: true,
    numberAssociations: [
      { number: 9, role: 'supporting', source: '2026 expanded research: 3 of 23 independent sources for Number 9, all part of the Mars-themed cluster.', sources: ['Solacely, "Crystals for Destiny Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-destiny-number-9', 'Solacely, "Crystals for Life Path Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-9', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-9-in-numerology/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'Existing supportingCrystals entry for Number 9 (numberKnowledge.js); now independently re-confirmed at exactly the 3-source Tier-A bar by the 2026 expanded research pass.',
  },
  { id: 'blue-lace-agate', name: 'Blue Lace Agate', aliases: [], materialType: 'Chalcedony', active: true,
    numberAssociations: [
      { number: 3, role: 'supporting', source: '2026 expanded research: 3 of 20 independent sources for Number 3.', sources: ['Solacely, "Crystals for Life Path Number 3" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-3', 'Orgonite Crystals — https://orgonitecrystals.com/blogs/news/numerology-and-crystals-discover-the-best-crystal-for-your-life-path-number', 'Soul Magik — https://soulmagik.in/blogs/blog/how-to-choose-crystal-bracelet-according-to-numerology'], evidenceTier: 'A' },
    ],
    sourceNotes: 'BRAND NEW stone, added by the 2026 expanded research pass -- not previously in this database.',
  },
  { id: 'blue-sapphire', name: 'Blue Sapphire', aliases: [], materialType: 'Corundum', numberAssociations: [], active: true, sourceNotes: 'Excluded on purpose. Blue Sapphire is the traditional Jyotish gemstone for Saturn/Number 8, appearing on 5 of the 22 Number-8 sources checked in the 2026 expanded pass (Navratan, Veraj Gems, Rashi Ratan Bhagya, Acharyaganesh, Lucky-Name-Numerology) -- but this project is crystals-only, so it is kept in the list (visible, not deleted) rather than scored.' },
  {
    id: 'carnelian', name: 'Carnelian', aliases: ['Red Carnelian'], materialType: 'Chalcedony', active: true,
    numberAssociations: [
      { number: 1, role: 'supporting', source: '2026 expanded research: 11 of 22 independent sources for Number 1.', sources: ['Solacely — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-1', 'Navratan — https://www.navratan.com/blog/lucky-stone-for-1-number-in-numerology', 'Moonberry Crystal Co — https://moonberrycrystalco.com/blogs/moonberry-musings/crystals-for-your-life-path-number', 'HealingCrystals369 — https://healingcrystals369.com/best-crystals-for-number-1-energy/', 'Satv Aura — https://satvaura.in/products/ruling-number-1-crystal-bracelet-with-manifestation-lock', 'Ratnakripa — https://www.ratnakripa.com/blogs/news/crystal-suggestion-2025', 'World of Oorja — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Astrotalk Store — https://astrotalk.store/products/mulank-1-sun-crystal-bracelet-for-women', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/'], evidenceTier: 'A' },
      { number: 3, role: 'supporting', source: '2026 expanded research: 5 of 20 independent sources for Number 3.', sources: ['Solacely, "Crystals for Life Path Number 3" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-3', 'AlignCrystalShop — https://aligncrystalshop.com/products/crystals-for-life-path-3', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'Navratan — https://www.navratan.com/blog/lucky-stones-for-numerology-number-3', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-3-in-numerology/'], evidenceTier: 'A' },
      { number: 9, role: 'supporting', source: '2026 expanded research: 5 of 23 independent sources for Number 9, all real bracelet-seller product listings.', sources: ['Crystal Empire Siri — https://crystalempiresiri.com/products/crystal-for-mulank-9-crystal-for-destiny-number-9-carnelian-bracelet', 'Astrotalk Store — https://astrotalk.store/products/mulank-9-mangal-crystal-bracelet-for-women', 'Dhanshree Gems — https://www.dhanshreegems.com/red-jasper-carnelian-bracelet.html', 'JustWowFactory — https://justwowfactory.com/products/moolank-bracelets-your-birth-number-your-power', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-9-bracelet'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Number 1 re-confirmed at a much larger scale (11 of 22 sources, up from 4 of 5); Numbers 3 and 9 also confirmed at Tier A.',
  },
  { id: 'cats-eye-stone', name: "Cat's Eye", aliases: [], materialType: 'Chrysoberyl (or quartz variant)', numberAssociations: [], active: true, sourceNotes: 'Excluded on purpose. Cat\'s Eye (Lehsunia) is the traditional Jyotish gemstone for Number 7 across the sources that mentioned it in the 2026 expanded pass (Navratan, MyRatna, AstroSage, Professional Numerology), and is also listed once as a traditional secondary stone for Number 2 (Navratan) -- excluded under the crystals-only policy, same as Ruby, Pearl, the Sapphires, Red Coral, Hessonite and Diamond.' },
  { id: 'charoite', name: 'Charoite', aliases: [], materialType: 'Silicate mineral', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  {
    id: 'citrine', name: 'Citrine', aliases: [], materialType: 'Quartz', active: true,
    numberAssociations: [
      { number: 1, role: 'supporting', source: '2026 expanded research: 9 of 22 independent sources for Number 1.', sources: ['Navratan — https://www.navratan.com/blog/lucky-stone-for-1-number-in-numerology', 'Krisiaart — https://krisiaart.com/products/life-path-number-1-healing-crystals-numerology-crystal-set', 'HealingCrystals369 — https://healingcrystals369.com/best-crystals-for-number-1-energy/', 'Orgonite Crystals — https://orgonitecrystals.com/blogs/news/numerology-and-crystals-discover-the-best-crystal-for-your-life-path-number', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-one-meaning-lucky-symbols-crystals-and-more', 'Rashi Ratan Bhagya — https://rashiratanbhagya.com/blog/post/gemstones-for-number-1-numerology', 'Satv Aura — https://satvaura.in/products/ruling-number-1-crystal-bracelet-with-manifestation-lock', 'Ratnakripa — https://www.ratnakripa.com/blogs/news/crystal-suggestion-2025', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-1/'], evidenceTier: 'A' },
      { number: 3, role: 'primary', source: '2026 expanded research: 10 of 20 independent sources for Number 3 — the clearest single-number consensus for this number, most often called its "signature" or "merchant\'s stone."', sources: ['Solacely, "Crystals for Life Path Number 3" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-3', 'AlignCrystalShop — https://aligncrystalshop.com/products/crystals-for-life-path-3', 'The Zen Crystals, "Moolank 3" — https://thezencrystals.com/blogs/news/moolank-3-ruling-number-3-personality-traits-strengths-challenges-best-crystals', 'World of Oorja (blog) — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Satv Aura — https://satvaura.in/products/ruling-number-3-crystal-bracelet-with-manifestation-lock', 'Kundli Sutra — https://kundlisutra.com/blogs/news/numerology-number-3-mulank-3-in-2026', 'Soul Magik — https://soulmagik.in/blogs/blog/how-to-choose-crystal-bracelet-according-to-numerology', 'Navratan — https://www.navratan.com/blog/lucky-stones-for-numerology-number-3', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-3-in-numerology/', 'himangshuin crystal-suggestion tool — https://himangshuin.github.io/crystal-suggestion-numerology/'], evidenceTier: 'A' },
      { number: 5, role: 'supporting', source: '2026 expanded research: 8 of 20 independent sources for Number 5, second only to Aquamarine and very frequently recommended together with it.', sources: ['Solacely, "Crystals for Destiny Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-5', 'Solacely, "Crystals for Life Path Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-5', 'World of Oorja (product) — https://worldofoorja.com/products/mulank-5-bracelet', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-5-ruling-number-5-personality-traits-strengths-challenges-best-crystals', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-5/', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'Etsy — https://www.etsy.com/listing/1565857576/life-path-number-5-bracelet-crystal', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html'], evidenceTier: 'A' },
      { number: 8, role: 'primary', source: '2026 expanded research: 8 of 22 independent sources for Number 8 — the strongest single pick in a genuinely crowded field. Garnet (7), Black Tourmaline (6), Hematite (6), Pyrite (5) and Tiger\'s Eye (5) all also independently clear the 3-source bar, so Number 8 remains a multi-stone cluster rather than a landslide, and each of those is kept as a supporting stone below rather than dropped.', sources: ['Numerologist.com — https://numerologist.com/crystals/crystals-and-numerology-how-to-pick-the-right-crystal-according-to-your-life-path-number', 'Solacely, "Crystals for Life Path Number 8" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-8', 'Astrology Answers — https://www.astrologyanswers.com/article/numerology-the-crystal-connection/', 'GemGlow — https://gemglow.in/blogs/news/life-path-8-personality-traits-strengths-top-crystals', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-8-in-numerology', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-8-in-numerology', 'Luximag — https://luximag.com/the-ultimate-crystal-guide-for-life-path-number-8/', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date'], evidenceTier: 'A' },
    ],
    sourceNotes: 'Rebuilt from the 2026 expanded research pass. Number 8\'s Citrine pick is now the best-evidenced single answer for that number, but honestly remains a plurality (8/22) rather than a majority -- see the other Number-8 stones below, all independently confirmed at Tier A too.',
  },
  {
    id: 'clear-quartz', name: 'Clear Quartz', aliases: [], materialType: 'Quartz', active: true,
    numberAssociations: [
      { number: 1, role: 'supporting', source: '2026 expanded research: 6 of 22 independent sources for Number 1.', sources: ['Solacely — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-1', 'Krisiaart — https://krisiaart.com/products/life-path-number-1-healing-crystals-numerology-crystal-set', 'HealingCrystals369 — https://healingcrystals369.com/best-crystals-for-number-1-energy/', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-1/', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers'], evidenceTier: 'A' },
      { number: 2, role: 'supporting', source: '2026 expanded research: 3 of 28 independent sources for Number 2.', sources: ['Veraj Gems — https://www.verajgems.com/the-ultimate-guide-to-gemstones-for-numerologys-gentle-souls-number-2/', 'World of Oorja (blog) — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Inner Healings with Pooja — https://www.innerhealingswithpooja.com/product/moolank-2-21120/'], evidenceTier: 'A' },
      { number: 7, role: 'supporting', source: '2026 expanded research: 6 of 26 independent sources for Number 7 (upgraded from a single-source mention in the earlier pass).', sources: ['Solacely — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-7', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-seven-meaning-lucky-symbols-crystals-and-more', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-7-ruling-number-7-personality-traits-strengths-challenges-best-crystals', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-7-mulank-7'], evidenceTier: 'A' },
      { number: 9, role: 'supporting', source: '2026 expanded research: 6 of 23 independent sources for Number 9.', sources: ['GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-9-traits-strengths-and-best-crystals', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-9-ruling-number-9-personality-traits-strengths-challenges-best-crystals', 'Navratan — https://www.navratan.com/blog/lucky-stones-for-number-9', 'Soul Magik — https://soulmagik.in/products/numerology-bracelet-9', 'JustWowFactory — https://justwowfactory.com/products/moolank-bracelets-your-birth-number-your-power', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-9-bracelet'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Numbers 1, 2, 7 and 9 all confirmed at Tier A -- Clear Quartz turned out to be one of the most broadly (if never primarily) supported crystals across the whole nine-number pass.',
  },
  {
    id: 'fluorite', name: 'Fluorite', aliases: [], materialType: 'Halide mineral', active: true,
    numberAssociations: [
      { number: 4, role: 'supporting', source: '2026 expanded research: 4 of 25 independent sources for Number 4.', sources: ['Solacely, "Crystals for Destiny Number 4" — https://solacely.co/blogs/numerology/crystals-for-destiny-number-4', 'GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-4-traits-strengths-and-best-crystals', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-4/', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-four-meaning-lucky-symbols-crystals-and-more'], evidenceTier: 'A' },
    ],
    sourceNotes: 'BRAND NEW stone, added by the 2026 expanded research pass -- not previously in this database.',
  },
  {
    id: 'hematite', name: 'Hematite', aliases: [], materialType: 'Iron oxide', active: true,
    numberAssociations: [
      { number: 4, role: 'supporting', source: '2026 expanded research: 8 of 25 independent sources for Number 4, part of a real three-way "grounding trio" with Black Tourmaline and Smoky Quartz that co-occur on most of the same pages.', sources: ['Solacely, "Crystals for Life Path Number 4" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-4', 'Solacely, "Crystals for Destiny Number 4" — https://solacely.co/blogs/numerology/crystals-for-destiny-number-4', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-4-traits-strengths-and-best-crystals', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-4-ruling-number-4-personality-traits-strengths-challenges-best-crystals', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-4/', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers'], evidenceTier: 'A' },
      { number: 8, role: 'supporting', source: '2026 expanded research: 6 of 22 independent sources for Number 8.', sources: ['Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-8-in-numerology', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-8-in-numerology', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'World of Oorja (product) — https://worldofoorja.com/products/mulank-8-bracelet', 'Gemstone Galaxy — https://www.gemstonegalaxy.in/products/mulank-8-saturn-strength-bracelet-for-birth-dates-8-17-26', 'Inner Healings with Pooja — https://www.innerhealingswithpooja.com/product/mulank-8-bracelet-the-bracelet-of-karma-wealth-inner-strength/'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: both Number 4 and Number 8 confirmed at a much larger scale (up from 1-2 sources each in the earlier pass).',
  },
  { id: 'howlite', name: 'Howlite', aliases: [], materialType: 'Borate mineral', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass (2 sources found for Number 6: Ratnakripa, Crystal Empire Siri).' },
  {
    id: 'jade', name: 'Jade', aliases: [], materialType: 'Jadeite/Nephrite', active: true,
    numberAssociations: [
      { number: 2, role: 'supporting', source: '2026 expanded research: 3 of 28 independent sources for Number 2.', sources: ['Navratan — https://www.navratan.com/blog/numerology-number-2-lucky-stones', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-2-in-numerology/', 'himangshuin crystal-suggestion tool — https://himangshuin.github.io/crystal-suggestion-numerology/'], evidenceTier: 'A' },
      { number: 6, role: 'supporting', source: '2026 expanded research: 5 of 26 independent sources for Number 6.', sources: ['Solacely, "Crystals for Destiny Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-6', 'Navratan — https://www.navratan.com/blog/best-stones-for-numerology-number-6', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-6-in-numerology', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-6-ruling-number-6-personality-traits-strengths-challenges-best-crystals', 'Hidden Numerology — https://hiddennumerology.com/numerology-planet-venus/'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: both Numbers 2 and 6 confirmed at Tier A.',
  },
  { id: 'jasper', name: 'Jasper', aliases: ['Red Jasper'], materialType: 'Chalcedony', active: true, numberAssociations: [
    { number: 9, role: 'primary', source: '2026 expanded research: 9 of 23 independent sources for Number 9 -- the top pick, appearing on both editorial content and the clear majority of real "Mulank/Ruling Number 9" bracelet listings, consistently tied to grounding Number 9\'s Mars rulership.', sources: ['Solacely, "Crystals for Destiny Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-destiny-number-9', 'Solacely, "Crystals for Life Path Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-9', 'World of Oorja — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Ratnakripa (product) — https://www.ratnakripa.com/products/birth-number-9-bracelet', 'Astrotalk Store — https://astrotalk.store/products/mulank-9-mangal-crystal-bracelet-for-women', 'Soul Magik — https://soulmagik.in/products/numerology-bracelet-9', 'Etsy — https://www.etsy.com/listing/1529963319/numerology-number-9-crystals-healing', 'JustWowFactory — https://justwowfactory.com/products/moolank-bracelets-your-birth-number-your-power', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-9-bracelet'], evidenceTier: 'A' },
  ], sourceNotes: 'The 2026 expanded research pass did NOT independently confirm the earlier "Red Jasper for Number 1" pairing at the new 3-source bar, so that association was dropped; Red Jasper is instead Number 9\'s best-supported primary pick, now with 9 independent sources (up from 2).' },
  { id: 'labradorite', name: 'Labradorite', aliases: [], materialType: 'Feldspar', active: true,
    numberAssociations: [
      { number: 4, role: 'supporting', source: '2026 expanded research: 3 of 25 independent sources for Number 4.', sources: ['Krisiaart — https://krisiaart.com/products/life-path-number-4-healing-crystals-numerology-crystal-set', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-4-in-numerology', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-4-bracelet'], evidenceTier: 'A' },
      { number: 7, role: 'supporting', source: '2026 expanded research: 5 of 26 independent sources for Number 7 (upgraded from a single-source mention in the earlier pass).', sources: ['Solacely — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-7', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-seven-meaning-lucky-symbols-crystals-and-more', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-7-ruling-number-7-personality-traits-strengths-challenges-best-crystals', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date', 'Etsy — https://www.etsy.com/listing/706804042/number-7-gemstone-kit-numerology-healing'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Numbers 4 and 7 both confirmed at Tier A.',
  },
  {
    id: 'lapis-lazuli', name: 'Lapis Lazuli', aliases: [], materialType: 'Metamorphic rock', active: true,
    numberAssociations: [
      { number: 7, role: 'supporting', source: '2026 expanded research: 9 of 26 independent sources for Number 7.', sources: ['Solacely — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-7', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-7-traits-strengths-and-best-crystals', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-7-in-numerology', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-7-ruling-number-7-personality-traits-strengths-challenges-best-crystals', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'MyRatna — https://myratna.com/blog/numerology-number-7-meaning-love-life-remedies/', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Starstell — https://www.starstell.com/blog/gemstone-selection-numerology-finding-the-perfect-pairing/'], evidenceTier: 'A' },
      { number: 8, role: 'supporting', source: '2026 expanded research: 4 of 22 independent sources for Number 8.', sources: ['Veraj Gems — https://www.verajgems.com/powerful-gemstones-for-number-8-in-numerology-a-guide-to-unlocking-prosperity-and-success/', 'Rashi Ratan Bhagya — https://rashiratanbhagya.com/blogs/post/gemstones-for-number-8-in-numerology', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-8-mulank-8', 'Astrotalk Store — https://astrotalk.store/products/mulank-8-shani-crystal-bracelet-for-women'], evidenceTier: 'A' },
      { number: 9, role: 'supporting', source: '2026 expanded research: 5 of 23 independent sources for Number 9.', sources: ['Solacely, "Crystals for Destiny Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-destiny-number-9', 'Solacely, "Crystals for Life Path Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-9', 'Acharyaganesh — https://acharyaganesh.shop/blogs/gemstone/the-perfect-gemstones-for-number-9-in-numerology', 'Navratan — https://www.navratan.com/blog/lucky-stones-for-number-9', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-9-bracelet'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Numbers 7, 8 and 9 all confirmed at Tier A.',
  },
  { id: 'larimar', name: 'Larimar', aliases: [], materialType: 'Pectolite', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  { id: 'malachite', name: 'Malachite', aliases: [], materialType: 'Carbonate mineral', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass (2 sources found for Number 8: Numerologist.com, Acharyaganesh).' },
  {
    id: 'moonstone', name: 'Moonstone', aliases: [], materialType: 'Feldspar', active: true,
    numberAssociations: [
      { number: 2, role: 'primary', source: '2026 expanded research: 21 of 28 independent sources for Number 2 (75%) -- by a wide margin the single strongest, most consistent crystal-number pairing found across the entire nine-number pass.', sources: ['Solacely, "Crystals for Life Path Number 2" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-2', 'Solacely, "Crystals for Destiny Number 2" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-2', 'Solacely (product) — https://solacely.co/products/ruling-number-2-bracelet', 'Krisiaart — https://krisiaart.com/products/life-path-number-2-healing-crystals-numerology-crystal-set', 'Veraj Gems — https://www.verajgems.com/the-ultimate-guide-to-gemstones-for-numerologys-gentle-souls-number-2/', 'Etsy — https://www.etsy.com/listing/1565855266/life-path-number-2-bracelet-crystal', 'Navratan — https://www.navratan.com/blog/numerology-number-2-lucky-stones', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-2-in-numerology/', 'World of Oorja (blog) — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'World of Oorja (product) — https://worldofoorja.com/products/mulank-2-bracelet', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-2-ruling-number-2-personality-traits-strengths-challenges-best-crystals', 'Astrotalk Store — https://astrotalk.store/products/mulank-2-moon-crystal-bracelet-for-women', 'Inner Healings with Pooja — https://www.innerhealingswithpooja.com/product/moolank-2-21120/', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-2-mulank-2', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers', 'Astrology Guide (Canada) — https://www.astrologyguide.ca/post/numerology-and-crystals', 'My Soul Mantra — https://www.mysoulmantra.com/products/certified-energised-ruling-number-2-two-bracelet-numerology', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-2/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'The strongest single finding of the entire 2026 expanded research pass -- 21 of 28 independently-fetched sources agree, several explicitly calling it the "signature" or "primary" stone for Number 2.',
  },
  { id: 'obsidian', name: 'Obsidian', aliases: ['Snowflake Obsidian'], materialType: 'Volcanic glass', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  { id: 'opalite', name: 'Opalite', aliases: [], materialType: 'Synthetic glass', numberAssociations: [], active: true, sourceNotes: 'Distinct from natural Opal (a different, traditional gem excluded from Number 6 for the same reason as other Jyotish substitute stones). No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  { id: 'pearl', name: 'Pearl', aliases: [], materialType: 'Organic gem', numberAssociations: [], active: true, sourceNotes: 'Excluded on purpose. Pearl is a traditional Jyotish gemstone for the Moon/Number 2 (and an organic gem, not a mineral crystal) -- it actually appeared on 9 of the 28 Number-2 sources checked in the 2026 expanded pass, more than several crystals that WERE included, but is kept out under the crystals-only policy. Moonstone is the strongly-confirmed Number 2 crystal instead.' },
  {
    id: 'peridot', name: 'Peridot', aliases: [], materialType: 'Olivine', active: true,
    numberAssociations: [
      { number: 6, role: 'supporting', source: '2026 expanded research: 3 of 26 independent sources for Number 6.', sources: ['Navratan — https://www.navratan.com/blog/best-stones-for-numerology-number-6', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-6-ruling-number-6-personality-traits-strengths-challenges-best-crystals', 'Etsy — https://www.etsy.com/listing/697528525/number-6-gemstone-kit-numerology-healing'], evidenceTier: 'A' },
    ],
    sourceNotes: 'BRAND NEW stone, added by the 2026 expanded research pass -- not previously in this database.',
  },
  { id: 'pietersite', name: 'Pietersite', aliases: [], materialType: 'Chalcedony', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  {
    id: 'pyrite', name: 'Pyrite', aliases: [], materialType: 'Iron sulfide', active: true,
    numberAssociations: [
      { number: 8, role: 'supporting', source: '2026 expanded research: 5 of 22 independent sources for Number 8 (up from 2 in the earlier pass).', sources: ['Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Solacely, "Crystals for Life Path Number 8" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-8', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-8-in-numerology', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'The earlier pass\'s Number 3 mention (2 sources) did not clear the new 3-source bar and was dropped; Number 8 is now confirmed at a larger scale.',
  },
  { id: 'rhodochrosite', name: 'Rhodochrosite', aliases: [], materialType: 'Carbonate mineral', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass.' },
  {
    id: 'rhodonite', name: 'Rhodonite', aliases: ['Pink Rhodonite'], materialType: 'Silicate mineral', active: true,
    numberAssociations: [
      { number: 6, role: 'supporting', source: '2026 expanded research: 7 of 26 independent sources for Number 6.', sources: ['Solacely, "Crystals for Destiny Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-6', 'Grimball Jewelers — https://grimballjewelers.com/numerology-number-6-stone/', 'Solacely, "Crystals for Life Path Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-6', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-six-meaning-lucky-symbols-crystals-and-more', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-6-ruling-number-6-personality-traits-strengths-challenges-best-crystals', 'In The Cavern — https://inthecavern.com/products/zeta-bracelet-ruling-number-6-bracelet', 'Ratnakripa (product) — https://www.ratnakripa.com/products/birth-number-6-bracelet'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Number 6 confirmed at a much larger scale (up from 2 sources).',
  },
  {
    id: 'rose-quartz', name: 'Rose Quartz', aliases: [], materialType: 'Quartz', active: true,
    numberAssociations: [
      { number: 6, role: 'primary', source: '2026 expanded research: 20 of 26 independent sources for Number 6 (77%) -- an overwhelming, cross-category consensus spanning editorial blogs, Indian gemstone/numerology sites, and commercial bracelet sellers alike.', sources: ['Solacely, "Crystals for Destiny Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-6', 'Navratan — https://www.navratan.com/blog/best-stones-for-numerology-number-6', 'Grimball Jewelers — https://grimballjewelers.com/numerology-number-6-stone/', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-6-in-numerology', 'Solacely, "Crystals for Life Path Number 6" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-6', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-six-meaning-lucky-symbols-crystals-and-more', 'GemGlow — https://gemglow.in/blogs/news/features-of-life-path-number-6-personality-traits-strengths-and-crystals', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'himangshuin crystal-suggestion tool — https://himangshuin.github.io/crystal-suggestion-numerology/', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-6-in-numerology/', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-6-ruling-number-6-personality-traits-strengths-challenges-best-crystals', 'World of Oorja — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Astrotalk Store — https://astrotalk.store/products/mulank-6-shukra-crystal-bracelet-for-women', 'In The Cavern — https://inthecavern.com/products/zeta-bracelet-ruling-number-6-bracelet', 'Etsy — https://www.etsy.com/listing/1565858366/life-path-number-6-bracelet-amethyst', 'My Soul Mantra — https://www.mysoulmantra.com/products/certified-energised-ruling-number-6-two-bracelet-numerology', 'Krisiaart — https://krisiaart.com/products/life-path-number-6-healing-crystals-numerology-crystal-set', 'Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Hidden Numerology — https://hiddennumerology.com/numerology-planet-venus/'], evidenceTier: 'A' },
      { number: 9, role: 'supporting', source: '2026 expanded research: 5 of 23 independent sources for Number 9, from the "compassion/personality" cluster rather than the Mars-grounding cluster.', sources: ['GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-9-traits-strengths-and-best-crystals', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-9-ruling-number-9-personality-traits-strengths-challenges-best-crystals', 'Astrology Guide (Canada) — https://www.astrologyguide.ca/post/numerology-and-crystals', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'Astrology Answers — https://www.astrologyanswers.com/article/numerology-the-crystal-connection/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'The earlier pass\'s Number 2 mention (1 source) did not clear the new 3-source bar and was dropped (Moonstone and Selenite are the confirmed Number 2 stones instead). Number 6 is now the second-strongest single finding of the whole expanded pass; Number 9 confirmed as a real, if secondary, cluster.',
  },
  {
    id: 'selenite', name: 'Selenite', aliases: [], materialType: 'Gypsum', active: true,
    numberAssociations: [
      { number: 2, role: 'supporting', source: '2026 expanded research: 7 of 28 independent sources for Number 2 -- the strongest secondary pick behind Moonstone.', sources: ['Solacely, "Crystals for Life Path Number 2" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-2', 'Solacely, "Crystals for Destiny Number 2" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-2', 'Navratan — https://www.navratan.com/blog/numerology-number-2-lucky-stones', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-2-ruling-number-2-personality-traits-strengths-challenges-best-crystals', 'Inner Healings with Pooja — https://www.innerhealingswithpooja.com/product/moolank-2-21120/', 'Astrology Guide (Canada) — https://www.astrologyguide.ca/post/numerology-and-crystals', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'The earlier pass\'s Number 7 mention (0 of 5 sources actually confirmed it) has been dropped now that the bar is 3+ sources; Number 2 is independently confirmed at a much larger scale.',
  },
  { id: 'sodalite', name: 'Sodalite', aliases: [], materialType: 'Silicate mineral', numberAssociations: [], active: true, sourceNotes: 'No number association reached the 3-source Tier-A bar in the 2026 expanded research pass (2 sources found for Number 3: Krisiaart, AlignCrystalShop; 1 source for Number 7: Solacely).' },
  { id: 'smoky-quartz', name: 'Smoky Quartz', aliases: [], materialType: 'Quartz', active: true,
    numberAssociations: [
      { number: 4, role: 'primary', source: '2026 expanded research: 10 of 25 independent sources for Number 4 -- the single most-cited crystal for this number, tied to grounding/stability themes that match Number 4\'s "practical, disciplined" archetype. Real three-way cluster with Black Tourmaline (9) and Hematite (8), which very frequently co-occur on the same pages as a "grounding trio."', sources: ['Solacely, "Crystals for Life Path Number 4" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-4', 'Solacely, "Crystals for Destiny Number 4" — https://solacely.co/blogs/numerology/crystals-for-destiny-number-4', 'GemGlow — https://gemglow.in/blogs/news/meaning-of-life-path-number-4-traits-strengths-and-best-crystals', 'World of Oorja — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'Aurora Gems — https://auroragems.com/crystals-gemstones/numerical-vibrations/number-4/', 'Moonberry Crystal Co — https://moonberrycrystalco.com/blogs/moonberry-musings/crystals-for-your-life-path-number', 'Orgonite Crystals — https://orgonitecrystals.com/blogs/news/numerology-and-crystals-discover-the-best-crystal-for-your-life-path-number', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers'], evidenceTier: 'A' },
    ],
    sourceNotes: 'Kept distinct from plain Clear Quartz since it is a materially different variety commonly sold as its own crystal. Number 4 confirmed at a much larger scale (up from 2 sources).',
  },
  {
    id: 'sunstone', name: 'Sunstone', aliases: [], materialType: 'Feldspar', active: true,
    numberAssociations: [
      { number: 1, role: 'supporting', source: '2026 expanded research: 10 of 22 independent sources for Number 1.', sources: ['Solacely — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-1', 'Moonberry Crystal Co — https://moonberrycrystalco.com/blogs/moonberry-musings/crystals-for-your-life-path-number', 'HealingCrystals369 — https://healingcrystals369.com/best-crystals-for-number-1-energy/', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-one-meaning-lucky-symbols-crystals-and-more', 'himangshuin crystal-suggestion tool — https://himangshuin.github.io/crystal-suggestion-numerology/', 'Rashi Ratan Bhagya — https://rashiratanbhagya.com/blog/post/gemstones-for-number-1-numerology', 'Ratnakripa — https://www.ratnakripa.com/blogs/news/crystal-suggestion-2025', 'Crystal Grids — https://crystalgrids.net/blogs/news/numerology-understanding-the-mystical-power-of-numbers', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: Number 1 confirmed at a much larger scale (up from 3 sources).',
  },
  {
    id: 'tiger-eye', name: 'Tiger Eye', aliases: ["Tiger's Eye"], materialType: 'Chalcedony (quartz)', active: true,
    numberAssociations: [
      { number: 1, role: 'supporting', source: '2026 expanded research: 3 of 22 independent sources for Number 1.', sources: ['Krisiaart — https://krisiaart.com/products/life-path-number-1-healing-crystals-numerology-crystal-set', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-1-mulank-1', 'Astrotalk Store — https://astrotalk.store/products/mulank-1-sun-crystal-bracelet-for-women'], evidenceTier: 'A' },
      { number: 4, role: 'supporting', source: '2026 expanded research: 4 of 25 independent sources for Number 4.', sources: ['Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-4-in-numerology', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-4-bracelet', 'Moonberry Crystal Co — https://moonberrycrystalco.com/blogs/moonberry-musings/crystals-for-your-life-path-number', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-four-meaning-lucky-symbols-crystals-and-more'], evidenceTier: 'A' },
      { number: 5, role: 'supporting', source: '2026 expanded research: 4 of 20 independent sources for Number 5.', sources: ['Solacely, "Crystals for Destiny Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-5', 'Etsy — https://www.etsy.com/listing/1529962781/numerology-number-5-crystals-healing', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-5-in-numerology', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-5-ruling-number-5-personality-traits-strengths-challenges-best-crystals'], evidenceTier: 'A' },
      { number: 7, role: 'supporting', source: '2026 expanded research: 3 of 26 independent sources for Number 7.', sources: ['Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-7-in-numerology', 'World of Oorja — https://worldofoorja.com/blogs/worldofoorja-blog/best-crystals-for-mulank-numerology-bracelet', 'AstroSage — https://www.astrosage.com/numerology/number-7-seven.asp'], evidenceTier: 'A' },
      { number: 8, role: 'supporting', source: '2026 expanded research: 5 of 22 independent sources for Number 8 (up from 1 in the earlier pass).', sources: ['Crystals.com — https://www.crystals.com/blogs/news/life-path-number', 'Solacely, "Crystals for Life Path Number 8" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-8', 'GemGlow — https://gemglow.in/blogs/news/life-path-8-personality-traits-strengths-top-crystals', 'Acharyaganesh — https://www.acharyaganesh.shop/blogs/gemstone/best-gemstones-for-number-8-in-numerology', 'Gemstone Galaxy — https://www.gemstonegalaxy.in/products/mulank-8-saturn-strength-bracelet-for-birth-dates-8-17-26'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass found Tiger Eye to be one of the most broadly-supported (if rarely primary) crystals across the whole nine-number pass -- confirmed for five separate numbers.',
  },
  {
    id: 'tourmaline', name: 'Tourmaline', aliases: ['Black Tourmaline'], materialType: 'Boron silicate', active: true,
    numberAssociations: [
      { number: 4, role: 'supporting', source: '2026 expanded research: 9 of 25 independent sources for Number 4, referring to the black variety -- part of a real three-way "grounding trio" with Smoky Quartz and Hematite.', sources: ['Solacely, "Crystals for Life Path Number 4" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-4', 'Solacely, "Crystals for Destiny Number 4" — https://solacely.co/blogs/numerology/crystals-for-destiny-number-4', 'Moonrise Crystals — https://moonrisecrystals.com/numerology/numerology-4-healing-crystals/', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-4-in-numerology', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-4-ruling-number-4-personality-traits-strengths-challenges-best-crystals', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-four-meaning-lucky-symbols-crystals-and-more', 'Crystal Empire Siri — https://crystalempiresiri.com/products/crystal-for-mulank-4-crystal-for-destiny-number-4-bracelet', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date'], evidenceTier: 'A' },
      { number: 8, role: 'supporting', source: '2026 expanded research: 6 of 22 independent sources for Number 8, referring to the black variety.', sources: ['Solacely, "Crystals for Life Path Number 8" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-8', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-8-in-numerology', 'Astrotalk Store — https://astrotalk.store/products/mulank-8-shani-crystal-bracelet-for-women', 'Gemstone Galaxy — https://www.gemstonegalaxy.in/products/mulank-8-saturn-strength-bracelet-for-birth-dates-8-17-26', 'Inner Healings with Pooja — https://www.innerhealingswithpooja.com/product/mulank-8-bracelet-the-bracelet-of-karma-wealth-inner-strength/', 'Krisiaart — https://krisiaart.com/products/life-path-number-8-healing-crystals-numerology-crystal-set'], evidenceTier: 'A' },
    ],
    sourceNotes: '2026 expanded research pass: both Numbers 4 and 8 confirmed at a much larger scale.',
  },
  { id: 'turquoise', name: 'Turquoise', aliases: [], materialType: 'Phosphate mineral', active: true,
    numberAssociations: [
      { number: 5, role: 'supporting', source: '2026 expanded research: 6 of 20 independent sources for Number 5.', sources: ['Solacely, "Crystals for Destiny Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-destiny-number-5', 'Solacely, "Crystals for Life Path Number 5" — https://www.solacely.co/en-us/blogs/numerology/crystals-for-life-path-number-5', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-5-in-numerology', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-5-ruling-number-5-personality-traits-strengths-challenges-best-crystals', 'GemGlow — https://gemglow.in/blogs/news/life-path-number-5-meaning-crystals-and-personality-traits', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-5-in-numerology/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'BRAND NEW confirmed association from the 2026 expanded research pass (previously too thin to score).',
  },
  {
    id: 'garnet', name: 'Garnet', aliases: [], materialType: 'Nesosilicate', active: true,
    numberAssociations: [
      { number: 1, role: 'primary', source: '2026 expanded research: 12 of 22 independent sources for Number 1 -- the single highest count found for this number, in a genuine four-way cluster with Carnelian (11), Sunstone (10) and Citrine (9), all comfortably Tier A.', sources: ['Solacely — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-1', 'Navratan — https://www.navratan.com/blog/lucky-stone-for-1-number-in-numerology', 'Krisiaart — https://krisiaart.com/products/life-path-number-1-healing-crystals-numerology-crystal-set', 'Astrology Answers — https://www.astrologyanswers.com/article/numerology-the-crystal-connection/', 'HealingCrystals369 — https://healingcrystals369.com/best-crystals-for-number-1-energy/', 'California Psychics — https://www.californiapsychics.com/blog/destiny-life-path/best-crystals-life-path.html', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-one-meaning-lucky-symbols-crystals-and-more', 'Satv Aura — https://satvaura.in/products/ruling-number-1-crystal-bracelet-with-manifestation-lock', 'Ratnakripa — https://www.ratnakripa.com/blogs/news/crystal-suggestion-2025', 'The Stardust Studio — https://thestarduststudio.com/products/numerology-no-1-mulank-1', 'Kristals — https://kristals.com/blogs/news/numerology-gemstones', 'JustWowFactory — https://justwowfactory.com/collections/numerology-ruling-number'], evidenceTier: 'A' },
      { number: 4, role: 'supporting', source: '2026 expanded research: 5 of 25 independent sources for Number 4.', sources: ['Krisiaart — https://krisiaart.com/products/life-path-number-4-healing-crystals-numerology-crystal-set', 'Navratan — https://www.navratan.com/blog/lucky-gemstones-for-number-4-in-numerology', 'The Zen Crystals (product) — https://thezencrystals.com/en-us/products/ruling-number-4-bracelet', 'Story of Awakening — https://www.storyofawakening.com/blogs/numerology/numerology-life-path-number-four-meaning-lucky-symbols-crystals-and-more', 'Ratnakripa — https://www.ratnakripa.com/blogs/news/crystal-suggestion-2025'], evidenceTier: 'A' },
      { number: 8, role: 'supporting', source: '2026 expanded research: 7 of 22 independent sources for Number 8 -- real, cross-tradition evidence (both editorial blogs and real "Mulank 8" bracelet-seller product listings) directly confirming what the client first noticed in a bracelet screenshot.', sources: ['GemGlow — https://gemglow.in/blogs/news/life-path-8-personality-traits-strengths-top-crystals', 'Veraj Gems — https://www.verajgems.com/powerful-gemstones-for-number-8-in-numerology-a-guide-to-unlocking-prosperity-and-success/', 'Rashi Ratan Bhagya — https://rashiratanbhagya.com/blogs/post/gemstones-for-number-8-in-numerology', 'The Miracle Hub — https://themiraclehub.in/blog/numerology-and-crystals-crystals-as-per-your-birth-date', 'Satvik Gems — https://satvikgems.com/best-healing-crystals-for-your-birthdays/', 'World of Oorja (product) — https://worldofoorja.com/products/mulank-8-bracelet', 'Gemstone Galaxy — https://www.gemstonegalaxy.in/products/mulank-8-saturn-strength-bracelet-for-birth-dates-8-17-26'], evidenceTier: 'A' },
      { number: 9, role: 'supporting', source: '2026 expanded research: 5 of 23 independent sources for Number 9.', sources: ['Solacely, "Crystals for Destiny Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-destiny-number-9', 'Solacely, "Crystals for Life Path Number 9" — https://www.solacely.co/blogs/numerology/crystals-for-life-path-number-9', 'Acharyaganesh — https://acharyaganesh.shop/blogs/gemstone/the-perfect-gemstones-for-number-9-in-numerology', 'The Zen Crystals — https://thezencrystals.com/blogs/news/moolank-9-ruling-number-9-personality-traits-strengths-challenges-best-crystals', 'Rashi Ratan Jaipur — https://rashiratanjaipur.net/Blog/gemstones-for-number-9-in-numerology/'], evidenceTier: 'A' },
    ],
    sourceNotes: 'The 2026 expanded pass turned Garnet into one of the best-evidenced stones in the whole database -- confirmed for four different numbers, including directly resolving the client\'s own Number 8 bracelet-screenshot question.',
  },
];

function getAllStones() {
  return CRYSTAL_37;
}

function getStoneById(id) {
  return CRYSTAL_37.find((s) => s.id === id) || null;
}

module.exports = { CRYSTAL_37, getAllStones, getStoneById };
