/**
 * KNOWLEDGE BASE
 * ==============
 * Structured interpretation records for numbers 1-9 and master numbers
 * 11/22/33. This module contains ZERO calculation logic — it only stores
 * and retrieves interpretation content, keyed by number.
 *
 * All text below is ORIGINAL content written for this application, not
 * copied from any book or website. Where traditional numerology draws on
 * historical texts, that influence is cited in `sources` rather than
 * reproduced — see server/knowledge/sources.js.
 *
 * Planetary symbolism is included ONLY for the Chaldean system, where
 * planetary rulership is a standard part of the tradition. It is omitted
 * for Pythagorean entries, since that system doesn't traditionally assign
 * planetary rulers to numbers.
 */

const { SOURCES } = require('./sources');

const NUMBER_RECORDS = {
  1: {
    number: 1,
    keywords: ['independence', 'leadership', 'originality', 'willpower'],
    positiveQualities: ['Self-reliant', 'Decisive', 'Pioneering', 'Ambitious'],
    challenges: ['Stubbornness', 'Impatience', 'Difficulty accepting help'],
    personalityThemes: 'Driven and self-directed, with a strong need to lead rather than follow.',
    careerThemes: ['Entrepreneurship', 'Management', 'Pioneering fields', 'Self-directed work'],
    relationshipThemes: 'Values independence in partners as much as in themselves.',
    moneyThemes: 'Tends to earn through initiative and risk-taking rather than steady employment.',
    strengths: ['Initiative', 'Confidence', 'Focus'],
    potentialChallenges: ['Overbearing tendencies', 'Difficulty compromising'],
    chaldeanPlanet: 'Sun',
    primaryColor: 'Red',
    supportingColors: ['Orange', 'Gold'],
    challengingColors: ['Black'],
    colorMeaning: 'Energy, initiative, and confidence.',
    primaryCrystal: 'Ruby',
    supportingCrystals: ['Sunstone', 'Red Jasper'],
    crystalMeaning: 'Traditionally used to support confidence, vitality, and leadership.',
    purposeTags: ['career', 'business'],
    compatibleNumbers: [2, 3, 5, 9],
    challengingNumbers: [8],
    driverInterpretation: 'As a Driver Number, 1 shows up in daily behaviour as assertiveness and a need to take the lead.',
    conductorInterpretation: 'As a Conductor Number, 1 points toward a life path built around forging new paths rather than following existing ones.',
    nameInterpretation: 'As a Name Number, 1 lends a commanding, self-assured public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 1 governs willpower and self-belief; its position in the bottom-middle cell ties it to the Practical plane and Will plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  2: {
    number: 2,
    keywords: ['cooperation', 'diplomacy', 'sensitivity', 'partnership'],
    positiveQualities: ['Empathetic', 'Diplomatic', 'Cooperative', 'Perceptive'],
    challenges: ['Over-accommodation', 'Indecision', 'Sensitivity to criticism'],
    personalityThemes: 'Intuitive and relationship-oriented, most comfortable working alongside others.',
    careerThemes: ['Counseling', 'Mediation', 'Partnerships', 'Team-based roles'],
    relationshipThemes: 'A natural partner — attentive and compromising, sometimes to the point of self-neglect.',
    moneyThemes: 'Tends toward steady, shared financial approaches rather than solo risk-taking.',
    strengths: ['Tact', 'Patience', 'Emotional intelligence'],
    potentialChallenges: ['Difficulty asserting own needs'],
    chaldeanPlanet: 'Moon',
    primaryColor: 'White',
    supportingColors: ['Cream', 'Silver'],
    challengingColors: ['Red'],
    colorMeaning: 'Calm, sensitivity, and receptivity.',
    primaryCrystal: 'Moonstone',
    supportingCrystals: ['Pearl', 'Rose Quartz'],
    crystalMeaning: 'Traditionally used to support intuition, calm, and harmonious relationships.',
    purposeTags: ['relationships', 'communication'],
    compatibleNumbers: [1, 6, 9],
    challengingNumbers: [],
    driverInterpretation: 'As a Driver Number, 2 shows up as gentleness and a preference for consensus over confrontation.',
    conductorInterpretation: 'As a Conductor Number, 2 points toward a life path centered on partnership, diplomacy, and bringing people together.',
    nameInterpretation: 'As a Name Number, 2 lends a warm, approachable public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 2 governs emotional sensitivity; its top-right position ties it to the Mental plane and Action plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  3: {
    number: 3,
    keywords: ['creativity', 'expression', 'optimism', 'communication'],
    positiveQualities: ['Charismatic', 'Creative', 'Sociable', 'Quick-witted'],
    challenges: ['Scattered focus', 'Overcommitting', 'Avoiding hard truths'],
    personalityThemes: 'Expressive and upbeat, drawn to creative and social outlets.',
    careerThemes: ['Writing', 'Performing arts', 'Marketing', 'Public speaking'],
    relationshipThemes: 'Warm and entertaining, needs a partner who can match a desire for variety.',
    moneyThemes: 'Income often tied to creative or communicative skill rather than routine work.',
    strengths: ['Expression', 'Adaptability', 'Humour'],
    potentialChallenges: ['Difficulty with follow-through'],
    chaldeanPlanet: 'Jupiter',
    primaryColor: 'Yellow',
    supportingColors: ['Purple', 'Pink'],
    challengingColors: ['Sea green'],
    colorMeaning: 'Optimism, expression, and sociability.',
    primaryCrystal: 'Yellow Sapphire',
    supportingCrystals: ['Citrine', 'Amber'],
    crystalMeaning: 'Traditionally used to support communication, optimism, and creative expression.',
    purposeTags: ['communication', 'personal'],
    compatibleNumbers: [1, 6],
    challengingNumbers: [7],
    driverInterpretation: 'As a Driver Number, 3 shows up as natural charm and a talent for self-expression.',
    conductorInterpretation: 'As a Conductor Number, 3 points toward a life path built around creativity, communication, and bringing joy to others.',
    nameInterpretation: 'As a Name Number, 3 lends a lively, magnetic public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 3 governs self-expression; its middle-left position ties it to the Emotional plane and Thought plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  4: {
    number: 4,
    keywords: ['structure', 'discipline', 'reliability', 'foundation'],
    positiveQualities: ['Methodical', 'Dependable', 'Hardworking', 'Practical'],
    challenges: ['Rigidity', 'Resistance to change', 'Overworking'],
    personalityThemes: 'Grounded and systematic, most comfortable with clear plans and routines.',
    careerThemes: ['Engineering', 'Finance', 'Administration', 'Construction'],
    relationshipThemes: 'Loyal and steady, showing love through consistency rather than grand gestures.',
    moneyThemes: 'Prefers stable, well-planned finances over speculation.',
    strengths: ['Discipline', 'Organisation', 'Endurance'],
    potentialChallenges: ['Difficulty adapting to sudden change'],
    chaldeanPlanet: 'Rahu (North Lunar Node)',
    primaryColor: 'Grey',
    supportingColors: ['Electric blue', 'Navy'],
    challengingColors: ['Light green'],
    colorMeaning: 'Stability, structure, and groundedness.',
    primaryCrystal: 'Hessonite',
    supportingCrystals: ['Smoky Quartz', 'Black Tourmaline'],
    crystalMeaning: 'Traditionally used to support grounding, discipline, and stability.',
    purposeTags: ['career', 'finance'],
    compatibleNumbers: [2, 8],
    challengingNumbers: [5],
    driverInterpretation: 'As a Driver Number, 4 shows up as reliability and a preference for order.',
    conductorInterpretation: 'As a Conductor Number, 4 points toward a life path centered on building lasting structures — literal or figurative.',
    nameInterpretation: 'As a Name Number, 4 lends a dependable, no-nonsense public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 4 governs discipline; its top-left position ties it to the Mental plane and Thought plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  5: {
    number: 5,
    keywords: ['freedom', 'change', 'adaptability', 'curiosity'],
    positiveQualities: ['Adaptable', 'Curious', 'Energetic', 'Resourceful'],
    challenges: ['Restlessness', 'Impulsiveness', 'Difficulty with routine'],
    personalityThemes: 'Adventurous and versatile, drawn to variety and new experience.',
    careerThemes: ['Travel-related work', 'Sales', 'Journalism', 'Non-routine work'],
    relationshipThemes: 'Needs room to breathe — thrives with a partner who values independence too.',
    moneyThemes: 'Income can be variable, often tied to changing circumstances or ventures.',
    strengths: ['Versatility', 'Quick thinking', 'Resilience'],
    potentialChallenges: ['Difficulty committing long-term'],
    chaldeanPlanet: 'Mercury',
    primaryColor: 'Light green',
    supportingColors: ['Light grey', 'White'],
    challengingColors: ['Grey'],
    colorMeaning: 'Adaptability, freedom, and quick thinking.',
    primaryCrystal: 'Emerald',
    supportingCrystals: ['Peridot', 'Aventurine'],
    crystalMeaning: 'Traditionally used to support adaptability, communication, and mental clarity.',
    purposeTags: ['communication', 'personal'],
    compatibleNumbers: [1, 7],
    challengingNumbers: [4],
    driverInterpretation: 'As a Driver Number, 5 shows up as restlessness and a hunger for new experience.',
    conductorInterpretation: 'As a Conductor Number, 5 points toward a life path defined by change, travel, and freedom from routine.',
    nameInterpretation: 'As a Name Number, 5 lends a dynamic, unpredictable public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 5 sits at the center, governing balance across every plane and arrow that passes through it.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  6: {
    number: 6,
    keywords: ['responsibility', 'harmony', 'nurturing', 'community'],
    positiveQualities: ['Nurturing', 'Responsible', 'Fair-minded', 'Community-oriented'],
    challenges: ['Self-sacrifice', 'Excess worry', 'Difficulty setting boundaries'],
    personalityThemes: 'Warm and duty-bound, often the one others turn to for support.',
    careerThemes: ['Healthcare', 'Teaching', 'Hospitality', 'Family business'],
    relationshipThemes: 'Deeply devoted, sometimes to a fault — needs to guard against over-giving.',
    moneyThemes: 'Often spends generously on family or community before self.',
    strengths: ['Compassion', 'Fairness', 'Reliability'],
    potentialChallenges: ['Difficulty prioritising own needs'],
    chaldeanPlanet: 'Venus',
    primaryColor: 'Blue',
    supportingColors: ['Pink', 'White'],
    challengingColors: ['Yellow'],
    colorMeaning: 'Harmony, relationships, and comfort.',
    primaryCrystal: 'Diamond',
    supportingCrystals: ['Opal', 'Rose Quartz'],
    crystalMeaning: 'Traditionally used to support love, harmony, and beauty in relationships.',
    purposeTags: ['relationships', 'personal'],
    compatibleNumbers: [2, 9],
    challengingNumbers: [3],
    driverInterpretation: 'As a Driver Number, 6 shows up as warmth and a natural sense of responsibility toward others.',
    conductorInterpretation: 'As a Conductor Number, 6 points toward a life path centered on caregiving, harmony, and community.',
    nameInterpretation: 'As a Name Number, 6 lends a trustworthy, nurturing public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 6 governs harmony; its bottom-right position ties it to the Practical plane and Action plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  7: {
    number: 7,
    keywords: ['introspection', 'analysis', 'wisdom', 'depth'],
    positiveQualities: ['Analytical', 'Intuitive', 'Independent-minded', 'Focused'],
    challenges: ['Withdrawal', 'Over-criticism', 'Difficulty opening up'],
    personalityThemes: 'Private and reflective, drawn to understanding what lies beneath the surface.',
    careerThemes: ['Research', 'Science', 'Philosophy/spirituality', 'Analysis-heavy roles'],
    relationshipThemes: 'Needs solitude to recharge; suits a partner who respects that need for space.',
    moneyThemes: 'Often approaches money analytically rather than emotionally.',
    strengths: ['Depth of thought', 'Independence', 'Insight'],
    potentialChallenges: ['Difficulty trusting others fully'],
    chaldeanPlanet: 'Ketu (South Lunar Node) / Neptune',
    primaryColor: 'Sea green',
    supportingColors: ['Light yellow', 'White'],
    challengingColors: ['Yellow'],
    colorMeaning: 'Introspection, depth, and quiet wisdom.',
    primaryCrystal: "Cat's Eye",
    supportingCrystals: ['Labradorite', 'Amethyst'],
    crystalMeaning: 'Traditionally used to support intuition, introspection, and spiritual insight.',
    purposeTags: ['personal', 'career'],
    compatibleNumbers: [5, 9],
    challengingNumbers: [3],
    driverInterpretation: 'As a Driver Number, 7 shows up as a reflective, somewhat guarded manner.',
    conductorInterpretation: 'As a Conductor Number, 7 points toward a life path centered on inquiry, study, or spiritual depth.',
    nameInterpretation: 'As a Name Number, 7 lends a thoughtful, enigmatic public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 7 governs analysis; its middle-right position ties it to the Emotional plane and Action plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  8: {
    number: 8,
    keywords: ['ambition', 'authority', 'achievement', 'material success'],
    positiveQualities: ['Driven', 'Strategic', 'Confident', 'Results-oriented'],
    challenges: ['Controlling tendencies', 'Work obsession', 'Difficulty delegating'],
    personalityThemes: 'Goal-oriented and authoritative, comfortable taking charge of large undertakings.',
    careerThemes: ['Business leadership', 'Finance', 'Real estate', 'High-stakes negotiation'],
    relationshipThemes: 'Provides generously, but needs to consciously make room for softness.',
    moneyThemes: 'Strong drive toward financial achievement and material security.',
    strengths: ['Ambition', 'Strategic thinking', 'Resilience under pressure'],
    potentialChallenges: ['Prioritising achievement over relationships'],
    chaldeanPlanet: 'Saturn',
    primaryColor: 'Black',
    supportingColors: ['Dark blue', 'Purple'],
    challengingColors: ['Red'],
    colorMeaning: 'Authority, discipline, and material achievement.',
    primaryCrystal: 'Blue Sapphire',
    supportingCrystals: ['Amethyst', 'Onyx'],
    crystalMeaning: 'Traditionally used to support discipline, ambition, and material success.',
    purposeTags: ['business', 'finance', 'career'],
    compatibleNumbers: [4, 6],
    challengingNumbers: [1],
    driverInterpretation: 'As a Driver Number, 8 shows up as ambition and a commanding presence.',
    conductorInterpretation: 'As a Conductor Number, 8 points toward a life path centered on achievement, authority, and material building.',
    nameInterpretation: 'As a Name Number, 8 lends a powerful, results-driven public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 8 governs ambition; its bottom-left position ties it to the Practical plane and Thought plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  9: {
    number: 9,
    keywords: ['compassion', 'idealism', 'universality', 'completion'],
    positiveQualities: ['Compassionate', 'Generous', 'Broad-minded', 'Idealistic'],
    challenges: ['Impracticality', 'Self-sacrifice', 'Difficulty letting go'],
    personalityThemes: 'Big-picture and altruistic, often drawn to causes larger than themselves.',
    careerThemes: ['Non-profit work', 'The arts', 'Humanitarian work', 'Advocacy'],
    relationshipThemes: 'Loving and selfless, needs a partner who won\u2019t take that generosity for granted.',
    moneyThemes: 'Often gives generously, sometimes at the expense of personal financial security.',
    strengths: ['Compassion', 'Vision', 'Generosity'],
    potentialChallenges: ['Difficulty with practical, day-to-day details'],
    chaldeanPlanet: 'Mars',
    primaryColor: 'Maroon',
    supportingColors: ['Crimson', 'Pink'],
    challengingColors: ['Sea green'],
    colorMeaning: 'Compassion, idealism, and quiet intensity.',
    primaryCrystal: 'Red Coral',
    supportingCrystals: ['Garnet', 'Bloodstone'],
    crystalMeaning: 'Traditionally used to support courage, compassion, and vitality.',
    purposeTags: ['relationships', 'personal'],
    compatibleNumbers: [1, 2, 6],
    challengingNumbers: [7],
    driverInterpretation: 'As a Driver Number, 9 shows up as warmth and an instinct to help others.',
    conductorInterpretation: 'As a Conductor Number, 9 points toward a life path centered on service, idealism, and completion of larger cycles.',
    nameInterpretation: 'As a Name Number, 9 lends a compassionate, larger-than-life public presence.',
    loshuInterpretation: 'In the Lo Shu grid, 9 governs idealism; its top-middle position ties it to the Mental plane and Will plane.',
    sources: [SOURCES.original, SOURCES.taylor1926],
  },
  11: {
    number: 11,
    keywords: ['intuition', 'idealism', 'inspiration', 'heightened sensitivity'],
    positiveQualities: ['Intuitive', 'Inspirational', 'Idealistic', 'Perceptive'],
    challenges: ['Nervous tension', 'Impracticality', 'Difficulty grounding big ideas'],
    personalityThemes: 'Carries the traits of 2 amplified to a more intense, spiritually-attuned degree.',
    careerThemes: ['Counseling', 'Teaching', 'Spiritual or inspirational work', 'The arts'],
    relationshipThemes: 'Deeply intuitive about others\u2019 needs, sometimes overwhelmed by that sensitivity.',
    moneyThemes: 'Financial stability often depends on channeling idealism into practical structure.',
    strengths: ['Insight', 'Inspiration', 'Empathy'],
    potentialChallenges: ['Living up to the number\u2019s own high ideals'],
    chaldeanPlanet: null,
    primaryColor: 'White',
    supportingColors: ['Silver', 'Violet'],
    challengingColors: ['Red'],
    colorMeaning: 'Amplified intuition and heightened sensitivity \u2014 shares 2\u2019s color themes, intensified.',
    primaryCrystal: 'Moonstone',
    supportingCrystals: ['Labradorite', 'Selenite'],
    crystalMeaning: 'Amplified intuition and spiritual insight \u2014 shares 2\u2019s crystal themes, intensified.',
    purposeTags: ['relationships', 'personal'],
    isMasterNumber: true,
    compatibleNumbers: [2, 6],
    challengingNumbers: [4],
    driverInterpretation: 'As a Driver Number (where applicable to the system used), 11 rarely appears since Driver Numbers fully reduce to 1-9 in this app\u2019s Mulank convention; it is included here for completeness within name-based calculations where master numbers are preserved.',
    conductorInterpretation: 'Included for completeness; Conductor Numbers in this app fully reduce to 1-9 per standard Bhagyank practice.',
    nameInterpretation: 'As a Name Number, 11 lends an unusually intuitive, idealistic public presence.',
    loshuInterpretation: 'Not directly applicable to the Lo Shu grid, which only uses digits 1-9.',
    sources: [SOURCES.original],
  },
  22: {
    number: 22,
    keywords: ['master builder', 'large-scale vision', 'discipline', 'manifestation'],
    positiveQualities: ['Visionary', 'Practical', 'Disciplined', 'Capable of large undertakings'],
    challenges: ['Pressure of high expectations', 'Overwhelm', 'Perfectionism'],
    personalityThemes: 'Carries the traits of 4 amplified — a builder capable of turning big visions into concrete results.',
    careerThemes: ['Large-scale business', 'Architecture', 'Institution-building', 'Engineering'],
    relationshipThemes: 'Steady and capable, though can prioritise ambitious goals over personal connection.',
    moneyThemes: 'Strong potential for material achievement through disciplined, large-scale effort.',
    strengths: ['Vision paired with practicality', 'Endurance', 'Leadership'],
    potentialChallenges: ['Living up to the number\u2019s own high expectations'],
    chaldeanPlanet: null,
    primaryColor: 'Grey',
    supportingColors: ['Earth tones', 'Navy'],
    challengingColors: ['Light green'],
    colorMeaning: 'Amplified stability and vision \u2014 shares 4\u2019s color themes, intensified.',
    primaryCrystal: 'Hessonite',
    supportingCrystals: ['Black Tourmaline', 'Hematite'],
    crystalMeaning: 'Amplified grounding and large-scale building capacity \u2014 shares 4\u2019s crystal themes, intensified.',
    purposeTags: ['career', 'business'],
    isMasterNumber: true,
    compatibleNumbers: [4, 8],
    challengingNumbers: [5],
    driverInterpretation: 'Included for completeness; Driver Numbers in this app fully reduce to 1-9 per standard Mulank practice.',
    conductorInterpretation: 'Included for completeness; Conductor Numbers in this app fully reduce to 1-9 per standard Bhagyank practice.',
    nameInterpretation: 'As a Name Number, 22 lends an unusually capable, builder-like public presence.',
    loshuInterpretation: 'Not directly applicable to the Lo Shu grid, which only uses digits 1-9.',
    sources: [SOURCES.original],
  },
  33: {
    number: 33,
    keywords: ['selfless service', 'compassion', 'healing', 'nurturing on a large scale'],
    positiveQualities: ['Deeply nurturing', 'Compassionate', 'Service-oriented', 'Healing presence'],
    challenges: ['Self-sacrifice taken to an extreme', 'Martyrdom', 'Neglecting own needs'],
    personalityThemes: 'Carries the traits of 6 amplified — guided by an unusually strong sense of service to others.',
    careerThemes: ['Healthcare', 'Counseling', 'Humanitarian leadership', 'Teaching'],
    relationshipThemes: 'Extraordinarily giving, needs conscious practice in receiving as well as giving.',
    moneyThemes: 'Often prioritises others\u2019 wellbeing over personal financial gain.',
    strengths: ['Compassion at scale', 'Healing presence', 'Selflessness'],
    potentialChallenges: ['Burnout from over-giving'],
    chaldeanPlanet: null,
    primaryColor: 'Blue',
    supportingColors: ['Rose gold', 'White'],
    challengingColors: ['Yellow'],
    colorMeaning: 'Amplified harmony and care \u2014 shares 6\u2019s color themes, intensified.',
    primaryCrystal: 'Diamond',
    supportingCrystals: ['Rose Quartz', 'Opal'],
    crystalMeaning: 'Amplified compassion and healing presence \u2014 shares 6\u2019s crystal themes, intensified.',
    purposeTags: ['relationships', 'personal'],
    isMasterNumber: true,
    compatibleNumbers: [6, 9],
    challengingNumbers: [1],
    driverInterpretation: 'Included for completeness; Driver Numbers in this app fully reduce to 1-9 per standard Mulank practice.',
    conductorInterpretation: 'Included for completeness; Conductor Numbers in this app fully reduce to 1-9 per standard Bhagyank practice.',
    nameInterpretation: 'As a Name Number, 33 lends an unusually compassionate, service-oriented public presence.',
    loshuInterpretation: 'Not directly applicable to the Lo Shu grid, which only uses digits 1-9.',
    sources: [SOURCES.original],
  },
};

function getNumberRecord(n) {
  return NUMBER_RECORDS[n] || NUMBER_RECORDS[((n - 1) % 9) + 1];
}

module.exports = { NUMBER_RECORDS, getNumberRecord };
